(function () {
  "use strict";

  const SCHEMA_VERSION = 2;
  const STORAGE_KEY = "star-expense-ledger-v1";
  const DEFAULT_CATEGORIES = ["门票", "专辑", "周边", "交通", "住宿", "会员", "应援", "其他"];
  const state = { records: [], categories: [], filters: { search: "", startDate: "", endDate: "", category: "" }, selectedCategory: "", hasSearched: false };
  const el = {};
  let toastTimer;

  ["addRecordButton", "manageCategoriesButton", "categoryFilter", "searchFilter", "startDateFilter", "endDateFilter", "clearFiltersButton", "filterForm", "recordList", "recordCount", "filteredNet", "searchResults", "searchResultCount", "searchResultList", "lastMeetingDays", "lastMeetingDate", "meetingCount", "statsScope", "expenseTotal", "expenseCount", "categoryChart", "monthlyChart", "recordDialog", "recordForm", "dialogTitle", "recordId", "recordDate", "recordItem", "recordCity", "recordVenue", "expenseItemsList", "addExpenseItemButton", "recordTotal", "recordNote", "formError", "closeDialogButton", "cancelDialogButton", "exportJsonButton", "importJsonButton", "importFileInput", "dataFileStatus", "exportCsvButton", "categoryDialog", "categoryList", "manageCategoryName", "categoryError", "closeCategoryButton", "addCategoryButton", "toast"].forEach((id) => { el[id] = document.getElementById(id); });

  initialize();

  function initialize() {
    const localData = loadLocalData();
    state.records = localData.records;
    state.categories = localData.categories;
    setDataFileStatus("");
    populateCategoryOptions();
    bindEvents();
    render();
  }

  function bindEvents() {
    el.addRecordButton.addEventListener("click", () => openRecordDialog());
    el.manageCategoriesButton.addEventListener("click", openCategoryDialog);
    el.closeDialogButton.addEventListener("click", closeRecordDialog);
    el.cancelDialogButton.addEventListener("click", closeRecordDialog);
    el.recordForm.addEventListener("submit", saveRecordFromForm);
    el.addExpenseItemButton.addEventListener("click", () => { if (addExpenseItemRow()) updateRecordTotal(); });
    el.expenseItemsList.addEventListener("input", updateRecordTotal);
    el.expenseItemsList.addEventListener("change", (event) => { if (event.target.matches(".expense-category")) refreshExpenseCategoryOptions(); updateRecordTotal(); });
    el.expenseItemsList.addEventListener("click", (event) => { const button = event.target.closest("[data-remove-expense]"); if (!button) return; if (el.expenseItemsList.children.length <= 1) return showFormError("至少保留一项费用明细。"); button.closest(".expense-item-row").remove(); refreshExpenseCategoryOptions(); updateRecordTotal(); });
    el.expenseItemsList.addEventListener("dragstart", handleExpenseDragStart);
    el.expenseItemsList.addEventListener("dragend", handleExpenseDragEnd);
    el.expenseItemsList.addEventListener("dragover", (event) => event.preventDefault());
    el.expenseItemsList.addEventListener("drop", handleExpenseDrop);
    el.clearFiltersButton.addEventListener("click", clearFilters);
    el.exportJsonButton.addEventListener("click", exportJson);
    el.importJsonButton.addEventListener("click", () => el.importFileInput.click());
    el.exportCsvButton.addEventListener("click", exportCsv);
    el.importFileInput.addEventListener("change", importJson);
    el.filterForm.addEventListener("submit", (event) => { event.preventDefault(); state.hasSearched = true; syncFiltersAndRender(); switchTab("search"); });
    document.querySelectorAll(".tab-button").forEach((button) => button.addEventListener("click", () => switchTab(button.dataset.tab)));
    el.recordList.addEventListener("click", handleRecordAction);
    el.searchResultList.addEventListener("click", handleRecordAction);
    el.recordDialog.addEventListener("click", (event) => { if (event.target === el.recordDialog) closeRecordDialog(); });
    el.closeCategoryButton.addEventListener("click", closeCategoryDialog);
    el.categoryDialog.addEventListener("click", (event) => { if (event.target === el.categoryDialog) closeCategoryDialog(); });
    el.categoryList.addEventListener("click", handleCategoryAction);
    el.categoryList.addEventListener("dragstart", handleCategoryDragStart);
    el.categoryList.addEventListener("dragend", handleCategoryDragEnd);
    el.categoryList.addEventListener("dragover", (event) => event.preventDefault());
    el.categoryList.addEventListener("drop", handleCategoryDrop);
    el.addCategoryButton.addEventListener("click", addCategory);
  }

  function serializeData() { return { schemaVersion: SCHEMA_VERSION, exportedAt: new Date().toISOString(), categories: state.categories, records: state.records }; }
  function setDataFileStatus(message) { if (el.dataFileStatus) el.dataFileStatus.textContent = message; }
  function parsePayload(payload) { if (!payload || payload.schemaVersion !== SCHEMA_VERSION) return null; const records = Array.isArray(payload.records) ? payload.records.map(migrateRecord).filter(isValidRecord) : null; if (!records) return null; const categories = uniqueCategories([...(Array.isArray(payload.categories) ? payload.categories : DEFAULT_CATEGORIES), ...records.flatMap((record) => record.items.map((item) => item.category))]); return { records, categories: categories.length ? categories : [...DEFAULT_CATEGORIES] }; }
  function loadLocalData() { try { const raw = localStorage.getItem(STORAGE_KEY); if (!raw) return { records: [], categories: [...DEFAULT_CATEGORIES] }; const parsed = JSON.parse(raw); const normalized = parsePayload(Array.isArray(parsed) ? { schemaVersion: SCHEMA_VERSION, records: parsed, categories: DEFAULT_CATEGORIES } : parsed); return normalized || { records: [], categories: [...DEFAULT_CATEGORIES] }; } catch (error) { return { records: [], categories: [...DEFAULT_CATEGORIES] }; } }
  function persist() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(serializeData())); setDataFileStatus(""); } catch (error) { setDataFileStatus("浏览器保存失败，请检查存储权限"); showToast("数据保存失败"); } }
  function exportJson() { download(`追星开销账本_备份_${localDate()}.json`, JSON.stringify(serializeData(), null, 2), "application/json;charset=utf-8"); showToast("JSON 备份已导出"); }
  async function importJson(event) { const file = event.target.files[0]; event.target.value = ""; if (!file) return; let backup; try { backup = JSON.parse(await file.text()); } catch (error) { return showToast("导入失败：文件不是有效的 JSON"); } const records = Array.isArray(backup && backup.records) ? backup.records.map(migrateRecord) : null; if (!backup || backup.schemaVersion !== SCHEMA_VERSION || !records || !records.every(isValidRecord)) return showToast("导入失败：备份格式无效"); if (!window.confirm(`备份中有 ${records.length} 笔活动。导入会覆盖当前浏览器数据，是否继续？`)) return; state.categories = uniqueCategories([...(Array.isArray(backup.categories) ? backup.categories : DEFAULT_CATEGORIES), ...records.flatMap((record) => record.items.map((expense) => expense.category))]); state.records = records; populateCategoryOptions(); clearFilters(); render(); persist(); showToast("备份已恢复到浏览器"); }

  function populateCategoryOptions() {
    const selected = el.categoryFilter.value;
    el.categoryFilter.replaceChildren(new Option("全部分类", ""));
    state.categories.forEach((category) => { el.categoryFilter.append(new Option(category, category)); });
    el.categoryFilter.value = state.categories.includes(selected) ? selected : "";
  }

  function syncFiltersAndRender() { state.filters = { search: el.searchFilter.value.trim().toLocaleLowerCase("zh-CN"), startDate: el.startDateFilter.value, endDate: el.endDateFilter.value, category: el.categoryFilter.value }; render(); }
  function clearFilters() { [el.searchFilter, el.startDateFilter, el.endDateFilter, el.categoryFilter].forEach((control) => { control.value = ""; }); state.hasSearched = false; syncFiltersAndRender(); el.searchResultList.replaceChildren(); }
  function filteredRecords() { const f = state.filters; return state.records.filter((record) => { const searchable = `${record.title} ${record.city} ${record.note} ${record.items.map((item) => item.name).join(" ")}`.toLocaleLowerCase("zh-CN"); const hasCategory = record.items.some((item) => item.category === f.category); return (!f.search || searchable.includes(f.search)) && (!f.startDate || record.endDate >= f.startDate) && (!f.endDate || record.startDate <= f.endDate) && (!f.category || hasCategory); }).sort((a, b) => b.startDate.localeCompare(a.startDate) || b.updatedAt.localeCompare(a.updatedAt)); }

  function sortRecords(records) { return [...records].sort((a, b) => b.startDate.localeCompare(a.startDate) || b.updatedAt.localeCompare(a.updatedAt)); }
  function render() { const records = filteredRecords(); renderLedger(sortRecords(state.records)); renderSearchResults(records); renderStats(records); renderMeetingCards(); el.filteredNet.textContent = `全部消费 ${currency(sum(state.records))}`; }

  function renderMeetingCards() { const today = localDate(); const meetingCategories = ["演唱会", "音乐节", "拼盘"]; const meetings = state.records.filter((record) => record.items.some((item) => meetingCategories.includes(item.category))); const last = meetings.filter((record) => record.startDate <= today).sort((a, b) => b.startDate.localeCompare(a.startDate))[0]; el.lastMeetingDays.innerHTML = last ? `${dayDifference(last.startDate, today)} <small>天</small>` : `-- <small>天</small>`; el.lastMeetingDate.textContent = last ? formatDate(last.startDate) : "暂无"; el.meetingCount.innerHTML = `${meetings.length} <small>次</small>`; }

  function renderLedger(records) {
    el.recordCount.textContent = `共 ${records.length} 笔记录`;
    if (!records.length) { const hasFilters = Object.values(state.filters).some(Boolean); el.recordList.innerHTML = `<div class="empty-state"><div>${hasFilters ? '<span class="empty-state-mark" aria-hidden="true">☆</span>' : '<img class="empty-state-image" src="assets/empty-state-character.png" alt="">'}<h3>${hasFilters ? "没有符合条件的记录" : "账本还是空的"}</h3><p>${hasFilters ? "调整或清除筛选条件后再看看。" : ""}</p>${hasFilters ? "" : '<button class="primary-button" type="button" data-action="add">＋ 记下第一笔</button>'}</div></div>`; return; }
    el.recordList.innerHTML = renderRecordCards(records);
  }

  function renderSearchResults(records) { el.searchResults.hidden = !state.hasSearched; if (!state.hasSearched) return; el.searchResultCount.textContent = `共 ${records.length} 笔记录`; el.searchResultList.innerHTML = records.length ? renderRecordCards(records) : '<div class="empty-state"><div><span class="empty-state-mark" aria-hidden="true">☆</span><h3>没有符合条件的记录</h3><p>调整或清除筛选条件后再看看。</p></div></div>'; }

  function renderRecordCards(records) { const cards = records.map((record) => { const details = record.items.map((expense) => `<div class="record-expense-row"><span class="tag">${escapeHtml(expense.category)}</span><span class="record-expense-content">${escapeHtml(expense.name)}</span><span class="record-expense-amount">${currency(expense.amountCents)}</span></div>`).join(""); return `<article class="record-card"><div class="record-card-heading"><h3>${escapeHtml(record.title)}${record.city ? ` · ${escapeHtml(record.city)}` : ""}${record.venue ? `<small>${escapeHtml(record.venue)}</small>` : ""}</h3><span>${escapeHtml(record.startDate)}${record.endDate !== record.startDate ? ` 至 ${escapeHtml(record.endDate)}` : ""}</span></div><div class="record-expense-table"><div class="record-expense-header"><span>分类</span><span>内容</span><span>金额</span></div>${details}</div><div class="record-card-total"><span>总金额</span><strong class="amount expense">${currency(record.amountCents)}</strong></div>${record.note ? `<div class="record-note">${escapeHtml(record.note)}</div>` : ""}<div class="record-card-actions"><button class="row-action" type="button" data-action="edit" data-id="${escapeHtml(record.id)}">编辑</button><button class="row-action" type="button" data-action="delete" data-id="${escapeHtml(record.id)}">删除</button></div></article>`; }).join(""); return `<div class="record-cards">${cards}</div>`; }

  function renderStats(records) { const total = sum(records); el.expenseTotal.textContent = currency(total); el.expenseCount.textContent = `${records.length} 笔`; el.statsScope.textContent = `统计范围：${Object.values(state.filters).some(Boolean) ? "当前筛选" : "全部流水"}（${records.length} 笔）`; renderPie(el.categoryChart, groupCategories(records)); renderAnnual(records); }
  function renderPie(container, data) { if (!data.length) { container.innerHTML = '<div class="chart-empty">暂无可统计的数据</div>'; return; } const colors = ["#e86a92", "#f3b562", "#79b7b1", "#8d86c9", "#e08f70", "#6e9ecf", "#a6b86b", "#c58ab8"]; const total = data.reduce((sum, item) => sum + item.value, 0); let cursor = 0; const stops = data.map((item, index) => { const start = cursor; cursor += item.value / total * 360; return `${colors[index % colors.length]} ${start}deg ${cursor}deg`; }).join(", "); const legend = data.map((item, index) => `<div class="pie-legend-row"><span class="pie-swatch" style="background:${colors[index % colors.length]}"></span><span>${escapeHtml(item.label)}</span><strong>${Math.round(item.value / total * 100)}%</strong><small>${currency(item.value)}</small></div>`).join(""); container.innerHTML = `<div class="pie-layout"><div class="pie-visual" style="background:conic-gradient(${stops})" role="img" aria-label="分类支出占比饼图"></div><div class="pie-legend">${legend}</div></div>`; }
  function renderAnnual(records) { const colors = ["#e86a92", "#f3b562", "#79b7b1", "#8d86c9", "#e08f70", "#6e9ecf", "#a6b86b", "#c58ab8"]; const years = new Map(); const categories = []; records.forEach((record) => { const year = record.startDate.slice(0, 4); const groups = years.get(year) || new Map(); record.items.forEach((item) => { groups.set(item.category, (groups.get(item.category) || 0) + item.amountCents); if (!categories.includes(item.category)) categories.push(item.category); }); years.set(year, groups); }); const data = [...years.entries()].sort(([a], [b]) => a.localeCompare(b)); if (!data.length) { el.monthlyChart.innerHTML = '<div class="chart-empty">暂无年度统计数据</div>'; return; } const totals = data.map(([, groups]) => [...groups.values()].reduce((sum, value) => sum + value, 0)); const max = Math.max(...totals, 1); const bars = data.map(([year, groups], yearIndex) => { const total = totals[yearIndex]; const segmentBase = total || 1; const segments = categories.filter((category) => groups.has(category)).map((category, categoryIndex) => `<span class="annual-bar-segment" style="height:${groups.get(category) / segmentBase * 100}%;background:${colors[categoryIndex % colors.length]}" title="${escapeHtml(category)}：${currency(groups.get(category))}"></span>`).join(""); return `<div class="annual-bar-item" title="${year}年：${currency(total)}"><span class="annual-bar-value">${currency(total)}</span><div class="annual-bar-track"><div class="annual-bar-stack" style="height:${Math.max(total / max * 100, 3)}%">${segments}</div></div><span class="annual-bar-label">${year}年</span></div>`; }).join(""); const legend = categories.map((category, index) => `<span class="annual-legend-item"><i style="background:${colors[index % colors.length]}"></i>${escapeHtml(category)}</span>`).join(""); el.monthlyChart.innerHTML = `<div class="annual-bars">${bars}</div><div class="annual-legend">${legend}</div>`; }
  function groupCategories(records) { const groups = new Map(); records.forEach((record) => record.items.forEach((item) => groups.set(item.category, (groups.get(item.category) || 0) + item.amountCents))); return [...groups.entries()].map(([label, value]) => ({ label, value })).sort((a, b) => b.value - a.value || a.label.localeCompare(b.label, "zh-CN")); }
  function sum(records) { return records.reduce((total, record) => total + record.amountCents, 0); }
  function dayDifference(from, to) { const start = new Date(`${from}T00:00:00`); const end = new Date(`${to}T00:00:00`); return Math.max(0, Math.round((end - start) / 86400000)); }
  function formatDate(value) { return value.replaceAll("-", "."); }

  function switchTab(tabName) { document.querySelectorAll(".tab-button").forEach((button) => { const active = button.dataset.tab === tabName; button.classList.toggle("is-active", active); button.setAttribute("aria-selected", String(active)); }); document.querySelectorAll(".page-panel").forEach((panel) => { const active = panel.dataset.panel === tabName; panel.classList.toggle("is-active", active); panel.hidden = !active; }); }
  function handleRecordAction(event) { const button = event.target.closest("button[data-action]"); if (!button) return; if (button.dataset.action === "add") return openRecordDialog(); const record = state.records.find((item) => item.id === button.dataset.id); if (!record) return; if (button.dataset.action === "edit") openRecordDialog(record); if (button.dataset.action === "delete") deleteRecord(record); }
  function openRecordDialog(record) { el.recordForm.reset(); el.formError.textContent = ""; el.recordId.value = record ? record.id : ""; el.dialogTitle.textContent = record ? "编辑活动" : "添加消费记录"; el.recordDate.value = record ? record.startDate : localDate(); el.recordItem.value = record ? record.title : ""; el.recordCity.value = record ? record.city : ""; el.recordVenue.value = record ? record.venue : ""; el.recordNote.value = record ? record.note : ""; el.expenseItemsList.replaceChildren(); (record ? record.items : [{ category: state.categories[0], name: "", amountCents: null }]).forEach(addExpenseItemRow); refreshExpenseCategoryOptions(); updateRecordTotal(); el.recordDialog.showModal(); el.recordItem.focus(); }
  function addExpenseItemRow(item) { const used = [...el.expenseItemsList.querySelectorAll(".expense-category")].map((select) => select.value); const lastCategory = used.at(-1); const start = state.categories.indexOf(lastCategory); const category = item && state.categories.includes(item.category) ? item.category : state.categories.slice(start + 1).find((name) => !used.includes(name)); if (!category) { showFormError("上一条分类之后已没有可用分类。"); return false; } const row = document.createElement("div"); row.className = "expense-item-row"; row.draggable = true; row.innerHTML = `<label class="field"><span>分类</span><select class="expense-category">${state.categories.map((name) => `<option value="${escapeHtml(name)}">${escapeHtml(name)}</option>`).join("")}</select></label><label class="field item-note-field"><span>内容</span><input class="expense-name" type="text" maxlength="80" placeholder="例如：内场、往返、双人间"></label><label class="field"><span>金额（元）</span><input class="expense-amount" type="number" min="0" step="0.01" inputmode="decimal" value="" placeholder=""></label><button class="remove-expense-item" type="button" data-remove-expense aria-label="删除费用项目">×</button>`; el.expenseItemsList.append(row); row.querySelector(".expense-category").value = category; row.querySelector(".expense-name").value = item ? item.name : ""; row.querySelector(".expense-amount").value = item && Number.isInteger(item.amountCents) ? (item.amountCents / 100).toFixed(2) : ""; refreshExpenseCategoryOptions(); return true; }
  function refreshExpenseCategoryOptions() { const selects = [...el.expenseItemsList.querySelectorAll(".expense-category")]; const selected = selects.map((select) => select.value); selects.forEach((select) => { const value = select.value; select.replaceChildren(...state.categories.map((category) => new Option(category, category, false, category === value))); [...select.options].forEach((option) => { option.disabled = option.value !== value && selected.includes(option.value); }); }); const start = state.categories.indexOf(selected.at(-1)); el.addExpenseItemButton.disabled = !state.categories.slice(start + 1).some((category) => !selected.includes(category)); }
  function handleExpenseDragStart(event) { const row = event.target.closest(".expense-item-row"); if (!row) return; event.dataTransfer.effectAllowed = "move"; event.dataTransfer.setData("text/plain", String([...el.expenseItemsList.children].indexOf(row))); row.classList.add("is-dragging"); }
  function handleExpenseDragEnd(event) { const row = event.target.closest(".expense-item-row"); if (row) row.classList.remove("is-dragging"); }
  function handleExpenseDrop(event) { event.preventDefault(); const target = event.target.closest(".expense-item-row"); const from = Number(event.dataTransfer.getData("text/plain")); const source = el.expenseItemsList.children[from]; if (!target || !source || source === target) return; el.expenseItemsList.insertBefore(source, target); }
  function updateRecordTotal() { const total = [...el.expenseItemsList.querySelectorAll(".expense-amount")].reduce((sum, input) => { const value = parseAmount(input.value); return sum + (Number.isInteger(value) ? value : 0); }, 0); el.recordTotal.textContent = currency(total); }
  function closeRecordDialog() { el.recordDialog.close(); el.formError.textContent = ""; }
  function saveRecordFromForm(event) { event.preventDefault(); const date = el.recordDate.value, title = el.recordItem.value.trim(), city = el.recordCity.value.trim(), venue = el.recordVenue.value.trim(), note = el.recordNote.value.trim(), items = [...el.expenseItemsList.querySelectorAll(".expense-item-row")].map((row) => ({ category: row.querySelector(".expense-category").value, name: row.querySelector(".expense-name").value.trim(), amountCents: parseAmount(row.querySelector(".expense-amount").value) })); if (!isValidDate(date)) return showFormError("请选择有效日期。"); if (!title) return showFormError("请填写活动名称。"); if (!items.length || new Set(items.map((expense) => expense.category)).size !== items.length || items.some((expense) => !state.categories.includes(expense.category) || !Number.isInteger(expense.amountCents) || expense.amountCents < 0)) return showFormError("每个分类只能添加一次，金额不能小于 0。"); const amountCents = items.reduce((total, expense) => total + expense.amountCents, 0), now = new Date().toISOString(), index = state.records.findIndex((record) => record.id === el.recordId.value), data = { startDate: date, endDate: date, type: "expense", amountCents, category: items[0].category, title, city, venue, item: title, items, note, updatedAt: now }; if (index >= 0) { state.records[index] = { ...state.records[index], ...data }; showToast("活动已更新"); } else { state.records.push({ id: createId(), ...data, createdAt: now }); showToast("活动已保存"); } persist(); closeRecordDialog(); render(); }
  function showFormError(message) { el.formError.textContent = message; }
  function deleteRecord(record) { const label = [record.title, record.city].filter(Boolean).join(" · "); if (!window.confirm(`确定删除活动“${label}”吗？删除后无法撤销。`)) return; state.records = state.records.filter((item) => item.id !== record.id); persist(); render(); showToast("记录已删除"); }

  function openCategoryDialog() { el.categoryError.textContent = ""; state.selectedCategory = state.categories[0] || ""; el.manageCategoryName.value = ""; renderCategoryList(); el.categoryDialog.showModal(); }
  function renderCategoryList() { el.categoryList.innerHTML = state.categories.map((category, index) => `<div class="category-list-row${category === state.selectedCategory ? " is-selected" : ""}" draggable="true" data-category="${escapeHtml(category)}"><span class="category-order">${index + 1}</span><strong>${escapeHtml(category)}</strong><div class="category-order-actions"><button type="button" class="row-action" data-category-action="edit" data-category="${escapeHtml(category)}">编辑</button><button type="button" class="row-action danger-action" data-category-action="delete" data-category="${escapeHtml(category)}">删除</button></div></div>`).join(""); }
  function handleCategoryAction(event) { const button = event.target.closest("[data-category-action]"); if (!button) return; const category = button.dataset.category; if (button.dataset.categoryAction === "edit") return editCategory(category); if (button.dataset.categoryAction === "delete") deleteCategory(category); }
  function editCategory(oldName) { const newName = window.prompt("请输入新的分类名称", oldName); if (newName === null) return; const trimmed = newName.trim(); if (!isValidCategory(trimmed)) return showCategoryError("分类名称不能为空，且不超过 30 个字"); if (trimmed !== oldName && state.categories.includes(trimmed)) return showCategoryError("这个分类已经存在"); if (trimmed === oldName) return; state.categories = state.categories.map((item) => item === oldName ? trimmed : item); state.records = state.records.map((record) => ({ ...record, items: record.items.map((expense) => expense.category === oldName ? { ...expense, category: trimmed } : expense), category: record.category === oldName ? trimmed : record.category })); state.selectedCategory = trimmed; persist(); populateCategoryOptions(); render(); renderCategoryList(); showToast("分类已改名"); }
  function handleCategoryDragStart(event) { const row = event.target.closest(".category-list-row"); if (row) { event.dataTransfer.effectAllowed = "move"; event.dataTransfer.setData("text/plain", row.dataset.category); row.classList.add("is-dragging"); } }
  function handleCategoryDragEnd(event) { const row = event.target.closest(".category-list-row"); if (row) row.classList.remove("is-dragging"); }
  function handleCategoryDrop(event) { event.preventDefault(); const target = event.target.closest(".category-list-row"); const sourceName = event.dataTransfer.getData("text/plain"); if (!target || !sourceName || target.dataset.category === sourceName) return; const from = state.categories.indexOf(sourceName), to = state.categories.indexOf(target.dataset.category); if (from < 0 || to < 0) return; const [moved] = state.categories.splice(from, 1); state.categories.splice(to, 0, moved); persist(); populateCategoryOptions(); renderCategoryList(); }
  function closeCategoryDialog() { el.categoryDialog.close(); el.categoryError.textContent = ""; }
  function addCategory() { const name = el.manageCategoryName.value.trim(); if (!isValidCategory(name)) return showCategoryError("分类名称不能为空，且不超过 30 个字"); if (state.categories.includes(name)) return showCategoryError("这个分类已经存在"); state.categories.push(name); persist(); populateCategoryOptions(); render(); openCategoryDialog(); el.manageCategoryName.value = ""; showToast("分类已新增"); }
  function deleteCategory(category = state.selectedCategory || state.categories[0]) { if (state.categories.length <= 1) return showCategoryError("至少保留一个分类"); const fallback = state.categories.find((item) => item !== category); if (!window.confirm(`删除“${category}”后，相关记录将改为“${fallback}”，是否继续？`)) return; state.categories = state.categories.filter((item) => item !== category); state.records = state.records.map((record) => ({ ...record, items: record.items.map((expense) => expense.category === category ? { ...expense, category: fallback } : expense), category: record.category === category ? fallback : record.category })); state.selectedCategory = state.categories[0]; persist(); populateCategoryOptions(); render(); renderCategoryList(); showToast("分类已删除"); }
  function showCategoryError(message) { el.categoryError.textContent = message; }

  function exportCsv() { const header = ["日期", "活动名称", "城市", "场馆名称", "分类", "内容", "金额（元）", "总金额（元）", "备注", "创建时间", "更新时间"]; const rows = [...state.records].sort((a, b) => b.startDate.localeCompare(a.startDate)).flatMap((record) => record.items.map((item) => [record.startDate, record.title, record.city, record.venue, item.category, item.name, (item.amountCents / 100).toFixed(2), (record.amountCents / 100).toFixed(2), record.note, record.createdAt, record.updatedAt])); const csv = [header, ...rows].map((row) => row.map(escapeCsv).join(",")).join("\r\n"); download("追星开销账本_" + localDate() + ".csv", "\ufeff" + csv, "text/csv;charset=utf-8"); showToast("CSV 已导出"); }
  function download(filename, content, mime) { const url = URL.createObjectURL(new Blob([content], { type: mime })); const link = document.createElement("a"); link.href = url; link.download = filename; document.body.append(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 0); }
  function escapeCsv(value) { const text = String(value ?? ""); return /[",\r\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }
  function parseAmount(value) { const text = String(value).trim(); if (!/^\d+(?:\.\d{1,2})?$/.test(text)) return NaN; const [yuan, cents = ""] = text.split("."); const result = Number(yuan) * 100 + Number(cents.padEnd(2, "0")); return Number.isSafeInteger(result) ? result : NaN; }
  function isValidDate(value) { if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return false; const [year, month, day] = value.split("-").map(Number); const date = new Date(year, month - 1, day); return date.getFullYear() === year && date.getMonth() === month - 1 && date.getDate() === day; }
  function localDate() { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")}`; }
  function createId() { return window.crypto && crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(16).slice(2)}`; }
  function currency(cents) { return new Intl.NumberFormat("zh-CN", { style: "currency", currency: "CNY", minimumFractionDigits: 2 }).format(cents / 100); }
  function escapeHtml(value) { return String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;"); }
  function isValidCategory(value) { return typeof value === "string" && value.trim().length > 0 && value.length <= 30; }
  function uniqueCategories(values) { return [...new Set(values.filter(isValidCategory).map((value) => value.trim()))]; }
  function migrateRecord(record) { if (!record || typeof record !== "object") return record; const { activityType, ...data } = record; const startDate = data.startDate || data.date; const title = data.title || data.item; const items = Array.isArray(data.items) && data.items.length ? data.items : [{ category: data.category, name: data.item, amountCents: data.amountCents }]; return { ...data, startDate, endDate: data.endDate || startDate, city: typeof data.city === "string" ? data.city : "", venue: typeof data.venue === "string" ? data.venue : "", type: "expense", title, item: title, items, amountCents: items.reduce((sum, item) => sum + (Number.isInteger(item.amountCents) ? item.amountCents : 0), 0) }; }
  function isValidRecord(record) { return Boolean(record) && typeof record.id === "string" && isValidDate(record.startDate) && isValidDate(record.endDate) && record.endDate >= record.startDate && Array.isArray(record.items) && record.items.length > 0 && record.items.every((item) => isValidCategory(item.category) && typeof item.name === "string" && Number.isInteger(item.amountCents) && item.amountCents >= 0) && Number.isInteger(record.amountCents) && record.amountCents === record.items.reduce((sum, item) => sum + item.amountCents, 0) && typeof record.title === "string" && record.title.trim().length > 0 && typeof record.city === "string" && typeof record.venue === "string" && typeof record.note === "string" && typeof record.createdAt === "string" && typeof record.updatedAt === "string"; }
  function showToast(message) { clearTimeout(toastTimer); el.toast.textContent = message; el.toast.classList.add("is-visible"); toastTimer = setTimeout(() => el.toast.classList.remove("is-visible"), 2400); }
})();
